[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[env]
Term = "alacritty"

[font]
size = 13

[font.normal]
family = "JetBrainsMono NFM"

[general]
import = ["~/.config/alacritty/themes/themes/hyper.toml"]
