theme = "noir"

[editor]
true-color = true

[editor.file-picker]
parents = false

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]
