theme = "noir"

[editor]
true-color = true
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning" 
