theme = "autumn_night"

[editor]
true-color = true
line-number = "relative"
end-of-line-diagnostics = "hint"
color-modes = true

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.search]
wrap-around = false

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning" 
