[language-server.rust-analyzer]
cargo.buildScripts.enable = "true"
config.check.command = "clippy"

[language-server.tinymist]
config = { exportPdf = "onType" }

[[language]]
name = "c"
formatter = { command = "clang-format" }
auto-format = true
