"ui.background" = { bg = "black", fg = "white" }
"ui.background.separator" = "white"
"ui.text" = "white"
"ui.window" = "white"
"ui.linenr" = "glass"
"ui.menu.selected" = { bg = "white", fg = "black" }
"ui.cursor" = { bg = "black_grey" }
"ui.cursor.primary" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "white", modifiers = ["bold"] }
"ui.selection" = { bg = "glass", fg = "white" }
"ui.virtual.inlay-hint" = "white_glass"
"ui.virtual.inlay-hint.type" = { fg = "white_glass", modifiers = ["italic"] }
"ui.virtual.ruler" = { bg = "glass" }
"ui.menu.scroll" = "white_glass"

type = { fg = "white", modifiers = ["italic"] }
keyword = "black_grey"
punctuation = "grey"
operator = "grey"
comment = "white_glass"

"markup.heading" = { fg = "white", modifiers = ["bold"] }

error = "red"
"diagnostic.error" = { underline = { color = "red", style = "line" } }
warning = "orange"
"diagnostic.warning" = { underline = { color = "orange", style = "line" } }
info = "blue"
"diagnostic.info" = { underline = { color = "blue", style = "line" } }
hint = "white"
"diagnostic.hint" = { underline = { color = "white", style = "line" } }

[palette]
black = "#000000"
white = "#ffffff"
grey = "#cccccc"
black_grey = "#888888"
white_glass = "#666666"
glass = "#3b3b3b"
red = "#ff0000"
orange = "#ffa500"
blue = "#00ffff"
