#!/bin/sh
riverctl map normal Super+Shift Return spawn alacritty
riverctl default-attach-mode below

riverctl map normal Super+Shift Q close

riverctl map normal Super+Shift E exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl background-color 0x000000
riverctl border-color-focused 0xffffff
riverctl border-color-unfocused 0x000000

riverctl hide-cursor when-typing enabled

riverctl keyboard-layout -options grp:rctrl_toggle "us,ru"

riverctl rule-add -app-id "*" ssd

riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.55 &
